// Package identity manages the local device's ed25519 key pair.
// See PRD §3.1.1 and §4.3.
//
// The private key is stored platform-specifically:
//   - Windows: %APPDATA%/Lanos/identity.key (DPAPI encrypted)
//   - macOS:   ~/Library/Application Support/Lanos/identity.key (Keychain wrapped)
//   - Linux:   ~/.config/lanos/identity.key (0600 permission)
//   - Android: app private dir + Keystore-wrapped AES key
//   - iOS:     Keychain (kSecAttrAccessibleAfterFirstUnlockThisDeviceOnly)
//
// Device ID = SHA256(public_key)[:8] hex. Used as mDNS TXT `pk-hash` (full 16 bytes hex)
// and in `lanos://connect` URIs.
package identity

import (
	"crypto/ed25519"
	"crypto/rand"
	"crypto/sha256"
	"encoding/hex"
	"encoding/pem"
	"errors"
	"fmt"
	"os"
	"path/filepath"
)

// Identity holds the local device key material.
type Identity struct {
	PrivED   ed25519.PrivateKey
	PubED    ed25519.PublicKey
	PubHash  string // first 16 bytes of SHA256(pub), hex
	DeviceID string // first 8 bytes of SHA256(pub), hex
}

// LoadOrCreate reads the identity from the platform keystore, or generates a
// new one if missing. The at-rest protection is platform-specific (see
// Keystore): plain 0600 file on Linux, DPAPI on Windows, Keychain on macOS.
func LoadOrCreate() (*Identity, error) {
	path, err := keyPath()
	if err != nil {
		return nil, err
	}
	return loadOrCreateWithKeystore(path, platformKeystore())
}

// loadOrCreateWithKeystore is the testable core of LoadOrCreate. It accepts
// an injected Keystore so tests can substitute a fake without touching the
// platform-specific storage.
func loadOrCreateWithKeystore(path string, ks Keystore) (*Identity, error) {
	if data, err := ks.Load(path); err == nil {
		return parse(data)
	} else if !errors.Is(err, ErrNotFound) {
		return nil, fmt.Errorf("read identity: %w", err)
	}
	return generate(path, ks)
}

// Ephemeral DH keys for the Noise XK handshake are generated by the
// flynn/noise package itself; this package only owns the long-term
// ed25519 identity.

func keyPath() (string, error) {
	dir, err := dataDir()
	if err != nil {
		return "", err
	}
	if err := os.MkdirAll(dir, 0o700); err != nil {
		return "", err
	}
	return filepath.Join(dir, "identity.key"), nil
}

func parse(data []byte) (*Identity, error) {
	block, _ := pem.Decode(data)
	if block == nil || block.Type != "LANOS IDENTITY" {
		return nil, errors.New("invalid identity file format")
	}
	if len(block.Bytes) != ed25519.PrivateKeySize {
		return nil, fmt.Errorf("invalid key size: %d", len(block.Bytes))
	}
	priv := ed25519.PrivateKey(block.Bytes)
	pub := priv.Public().(ed25519.PublicKey)
	return fromKeys(priv, pub), nil
}

func generate(path string, ks Keystore) (*Identity, error) {
	pub, priv, err := ed25519.GenerateKey(rand.Reader)
	if err != nil {
		return nil, fmt.Errorf("generate key: %w", err)
	}
	block := &pem.Block{
		Type:  "LANOS IDENTITY",
		Bytes: []byte(priv),
	}
	data := pem.EncodeToMemory(block)
	if err := ks.Save(path, data); err != nil {
		return nil, fmt.Errorf("write identity: %w", err)
	}
	return fromKeys(priv, pub), nil
}

func fromKeys(priv ed25519.PrivateKey, pub ed25519.PublicKey) *Identity {
	sum := sha256.Sum256([]byte(pub))
	return &Identity{
		PrivED:   priv,
		PubED:    pub,
		PubHash:  hex.EncodeToString(sum[:16]),
		DeviceID: hex.EncodeToString(sum[:8]),
	}
}

// dataDir returns the platform-specific Lanos user data root directory.
// Mirrors PRD §5.3 data directory structure.
func dataDir() (string, error) {
	switch runtimeGOOS() {
	case "windows":
		appdata := os.Getenv("APPDATA")
		if appdata == "" {
			return "", errors.New("APPDATA not set")
		}
		return filepath.Join(appdata, "Lanos"), nil
	case "darwin":
		home, err := os.UserHomeDir()
		if err != nil {
			return "", err
		}
		return filepath.Join(home, "Library", "Application Support", "Lanos"), nil
	default: // linux and others
		home, err := os.UserHomeDir()
		if err != nil {
			return "", err
		}
		return filepath.Join(home, ".config", "lanos"), nil
	}
}
